"""Move show_price from MenuOption to MenuOptionGroup

Revision ID: 05ccfd0e4c8a
Revises: b9ec658e1dc8
Create Date: 2026-02-17 20:26:35.067403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05ccfd0e4c8a'
down_revision = 'b9ec658e1dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_option', schema=None) as batch_op:
        batch_op.drop_column('show_price')

    with op.batch_alter_table('menu_option_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_price', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_option_group', schema=None) as batch_op:
        batch_op.drop_column('show_price')

    with op.batch_alter_table('menu_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_price', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
