"""add toss merchant fields to store

Revision ID: 08f669ab058f
Revises: c1a2b3d4e5f6
Create Date: 2026-03-19 03:19:42.551797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f669ab058f'
down_revision = 'c1a2b3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toss_merchant_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('toss_business_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('toss_business_number')
        batch_op.drop_column('toss_merchant_id')

    # ### end Alembic commands ###
