"""Add legal info fields to store

Revision ID: 34fdbd88fcec
Revises: 7c9caea63dff
Create Date: 2026-02-17 05:06:35.803756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fdbd88fcec'
down_revision = '7c9caea63dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('representative_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tel', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('tel')
        batch_op.drop_column('address')
        batch_op.drop_column('representative_name')
        batch_op.drop_column('business_number')

    # ### end Alembic commands ###
