"""Add request_id to StaffCallLog

Revision ID: 7c9caea63dff
Revises: b7839db61562
Create Date: 2026-02-17 02:28:46.504070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9caea63dff'
down_revision = 'b7839db61562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_call_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_call_log', schema=None) as batch_op:
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
