"""Add receipt header and footer to store

Revision ID: a3ef3d10fe5d
Revises: 34fdbd88fcec
Create Date: 2026-02-17 06:08:31.251215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ef3d10fe5d'
down_revision = '34fdbd88fcec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_header', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('receipt_footer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_column('receipt_footer')
        batch_op.drop_column('receipt_header')

    # ### end Alembic commands ###
