"""Add show_price to MenuOption

Revision ID: b9ec658e1dc8
Revises: a3ef3d10fe5d
Create Date: 2026-02-17 20:12:10.846426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ec658e1dc8'
down_revision = 'a3ef3d10fe5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_price', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_option', schema=None) as batch_op:
        batch_op.drop_column('show_price')

    # ### end Alembic commands ###
