"""add terminal_token table

Revision ID: bd2139d2a99d
Revises: 33e4eac8364d
Create Date: 2026-03-18 07:15:54.396878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd2139d2a99d'
down_revision = '33e4eac8364d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('is_pos',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.drop_constraint('store_id', type_='unique')
        batch_op.drop_index('store_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.create_index('store_id', ['store_id', 'table_id', 'first_order_time'], unique=False)
        batch_op.create_unique_constraint('store_id', ['store_id', 'table_id', 'first_order_time'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('is_pos',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
