"""add terminal_token table

Revision ID: bd2139d2a99d
Revises: 33e4eac8364d
Create Date: 2026-03-18 07:15:54.396878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd2139d2a99d'
down_revision = '33e4eac8364d'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()

    # order.is_pos nullable 변경
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('is_pos',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # table_payment_list: FK → unique constraint 순서로 조건부 삭제
    fk_exists = bind.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS "
        "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='table_payment_list' "
        "AND CONSTRAINT_NAME='table_payment_list_ibfk_1' AND CONSTRAINT_TYPE='FOREIGN KEY'"
    )).scalar()
    if fk_exists:
        op.execute(sa.text("ALTER TABLE table_payment_list DROP FOREIGN KEY table_payment_list_ibfk_1"))

    uc_exists = bind.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS "
        "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='table_payment_list' "
        "AND CONSTRAINT_NAME='store_id' AND CONSTRAINT_TYPE='UNIQUE'"
    )).scalar()
    if uc_exists:
        op.execute(sa.text("ALTER TABLE table_payment_list DROP INDEX store_id"))

    # FK 지원용 단일 인덱스 생성 (없을 때만)
    ix_exists = bind.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.STATISTICS "
        "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='table_payment_list' "
        "AND INDEX_NAME='ix_tpl_store_id'"
    )).scalar()
    if not ix_exists:
        op.execute(sa.text("CREATE INDEX ix_tpl_store_id ON table_payment_list (store_id)"))

    # FK 복원 (없을 때만)
    fk_still_exists = bind.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS "
        "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='table_payment_list' "
        "AND CONSTRAINT_NAME='table_payment_list_ibfk_1' AND CONSTRAINT_TYPE='FOREIGN KEY'"
    )).scalar()
    if not fk_still_exists:
        op.execute(sa.text(
            "ALTER TABLE table_payment_list ADD CONSTRAINT table_payment_list_ibfk_1 "
            "FOREIGN KEY (store_id) REFERENCES store(id)"
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_payment_list', schema=None) as batch_op:
        batch_op.create_index('store_id', ['store_id', 'table_id', 'first_order_time'], unique=False)
        batch_op.create_unique_constraint('store_id', ['store_id', 'table_id', 'first_order_time'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('is_pos',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
